name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Python application"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Deploy to EC2
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          # Save the SSH key and set permissions
          mkdir -p ~/.ssh
          echo "${SSH_KEY}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/home/ec2-user/.ssh/id_rsa
          
          # Add the EC2 host to known_hosts to prevent SSH prompts
          ssh-keyscan -H $SERVER_HOST >> ~/home/ec2-user/.ssh/known_hosts
          
          # SSH into the EC2 instance and deploy the application
          ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST << 'EOF'
            cd /home/ec2-user/my_python_app
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart my_python_app
          EOF
