name: Python application

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'backend/**'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Test with pytest
      id: run_tests
      run: |
        pytest

    - name: Evaluate Test Results
      if: steps.run_tests.outcome == 'failure'
      run: |
       echo "Tests failed. Setting job status to failed."
       exit 1
    - name: Tests Passed
      if: steps.run_tests.outcome == 'success'
      run: echo "Tests passed successfully!"
